### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by jasii** [hfern/winix#1]
I recently got a c545 and I've been wanting to automate it and possibly add it to my home assistant. I found your repo, but I'm not sure how to run your scripts. I'm familiar with python but not with makefiles and setup scripts. Could you please write something up in the readme so I could get this running on my system?

**Comment by dgsharpe** [comment]
@jasii You don't need to bother with makefiles or setup scripts. If you simply install this package with pip, i.e. `pip install winix`, that will install the winixctl command on your system, at which point you can use all the commands.

If you don't want to use pip to install it, or if you want to edit the code to your taste and run it, simply run `python setup.py install` in the main directory of the repo. That will install the code in its present state (edited or unedited) to your system and give you the winixctl command.

**Comment by jasii** [comment]
Thank you, I got it running after the docs were updated a couple weeks back. It's been working great! I would like figure out how to wrap a home assistant integration around this, but I don't really have the time. I'm sure a lot of people use Winix c545, they're the only ones sold at Costco around where I live.
@hfern would you mind if I post your repo in the Home Assistant community forums to peek interest of others who may want to contribute?

**Comment by hfern** [comment]
@jasii go for it! I hope this can help other people!
