### ISSUE TITLE
Control multiple devices?

### ISSUE THREAD

**Issue by ngaustad** [hfern/winix#6]
The devices command lists all connected devices, however I'm not really seeing how I can choose which device I'm controlling, am I missing something?

**Comment by hfern** [comment]
Hi there @ngaustad! I just added rudimentary support for multiple devices to the code. I published the new version as `0.3.0` so you may need to run `pip install -U winix` to get it.

Here are some usage notes: https://github.com/hfern/winix#multi-device-support

Please let me know if this works for you!

**Comment by ngaustad** [comment]
Working great, thanks for the quick turn around!

**Comment by hfern** [comment]
Glad I could help :smile:
